# Note: The AccessKey and AccessSecret must never be push to a public available repository
# This solution is later-on going to be replaced by assigning roles to EC2 instances.

aws-slack-bot:
    restart: always
    image: vi-dev:5000/aws-slack-bot
    container_name: aws-slack-bot
    environment:
        AWS_ACCESS_KEY_ID: AKIAJAKADNUH5HLBCZWQ
        AWS_SECRET_ACCESS_KEY: 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